FROM node:latest

#Update NPM
RUN npm install -g npm@latest


#Clearing 
RUN rm -rf node_modules/

#Setting working Directory
WORKDIR /usr/src/app

RUN KEY_FILE=keys/server_key.pem \
 && CRT_FILE=keys/server_cert.pem \
 && mkdir keys -p \
 && if [ -f $FILE ]; then \
  openssl req -x509 -newkey rsa:4096 -keyout $KEY_FILE -out $CRT_FILE -days 365 -nodes -subj "/C=GB/ST=Liverpool/L=Liverpool/O=Haven Protocol Organization/OU=IT Department/CN=localhost"; \
 fi


#Copying sources on working directory
COPY . .

#Expose Node port
EXPOSE 5000

#Build from source
RUN npm install



#Start npm
CMD [ "npm", "start" ]
