FROM node:latest

#Update NPM
RUN npm install -g npm@latest 


#Clearing 
RUN rm -rf client/node_modules/

#Setting working Directory
WORKDIR /usr/src/app


#Copying sources on working directory
COPY client/. .

#Expose Node port
EXPOSE 3000

#Build from source
RUN npm install

#Start npm
CMD [ "npm", "start" ]
